#
# Makefile for IIO Light sensors
#

obj-$(CONFIG_ADJD_S311)		+= adjd_s311.o
obj-$(CONFIG_SENSORS_LM3533)	+= lm3533-als.o
obj-$(CONFIG_VCNL4000)		+= vcnl4000.o
obj-$(CONFIG_HID_SENSOR_ALS)	+= hid-sensor-als.o
obj-$(CONFIG_SENSORS_MAX44005)	+= max44005.o
