cmd_drivers/gpu/arm/mali/__malidrv_build_info.o := arm-linux-gnueabihf-gcc -Wp,-MD,drivers/gpu/arm/mali/.__malidrv_build_info.o.d  -nostdinc -isystem /usr/lib/gcc-cross/arm-linux-gnueabihf/5/include  -I/home/arturo/clickarm_3.8.18.30_IMASD/arch/arm/include -Iarch/arm/include/generated  -Iinclude -I/home/arturo/clickarm_3.8.18.30_IMASD/arch/arm/include/uapi -Iarch/arm/include/generated/uapi -I/home/arturo/clickarm_3.8.18.30_IMASD/include/uapi -Iinclude/generated/uapi -include /home/arturo/clickarm_3.8.18.30_IMASD/include/linux/kconfig.h -Iubuntu/include  -D__KERNEL__ -mlittle-endian -Iarch/arm/mach-exynos/include -Iarch/arm/plat-samsung/include -Wall -Wundef -Wstrict-prototypes -Wno-trigraphs -fno-strict-aliasing -fno-common -Werror-implicit-function-declaration -Wno-format-security -fno-delete-null-pointer-checks -std=gnu89 -O2 -fno-dwarf2-cfi-asm -mabi=aapcs-linux -mno-thumb-interwork -funwind-tables -marm -D__LINUX_ARM_ARCH__=7 -march=armv7-a -msoft-float -Uarm -Wframe-larger-than=1024 -fno-stack-protector -Wno-unused-but-set-variable -fomit-frame-pointer -fno-inline-functions-called-once -Wdeclaration-after-statement -Wno-pointer-sign -fno-strict-overflow -fconserve-stack -DCC_HAVE_ASM_GOTO -Idrivers/gpu/arm/mali/linux/license/gpl -DMALI_PP_SCHEDULER_FORCE_NO_JOB_OVERLAP=0 -DMALI_PP_SCHEDULER_KEEP_SUB_JOB_STARTS_ALIGNED=0 -DMALI_PP_SCHEDULER_FORCE_NO_JOB_OVERLAP_BETWEEN_APPS=0 -DMALI_STATE_TRACKING=1 -DMALI_OS_MEMORY_KERNEL_BUFFER_SIZE_IN_MB=16 -DUSING_GPU_UTILIZATION=0 -DMALI_ENABLE_CPU_CYCLES=0 -DMALI_UPPER_HALF_SCHEDULING -Idrivers/gpu/arm/mali -Idrivers/gpu/arm/mali/include -Idrivers/gpu/arm/mali/common -Idrivers/gpu/arm/mali/linux -Idrivers/gpu/arm/mali/platform -DSVN_REV_STRING=\"-10784cd\"    -D"KBUILD_STR(s)=\#s" -D"KBUILD_BASENAME=KBUILD_STR(__malidrv_build_info)"  -D"KBUILD_MODNAME=KBUILD_STR(mali)" -c -o drivers/gpu/arm/mali/__malidrv_build_info.o drivers/gpu/arm/mali/__malidrv_build_info.c

source_drivers/gpu/arm/mali/__malidrv_build_info.o := drivers/gpu/arm/mali/__malidrv_build_info.c

deps_drivers/gpu/arm/mali/__malidrv_build_info.o := \

drivers/gpu/arm/mali/__malidrv_build_info.o: $(deps_drivers/gpu/arm/mali/__malidrv_build_info.o)

$(deps_drivers/gpu/arm/mali/__malidrv_build_info.o):
